export const GET_COUNTIES_REQUEST = 'GET_COUNTIES_REQUEST';
export const GET_COUNTIES_SUCCESS = 'GET_COUNTIES_SUCCESS';
export const GET_COUNTIES_FAILURE = 'GET_COUNTIES_FAILURE';

export const GET_SUB_COUNTIES_REQUEST = 'GET_SUB_COUNTIES_REQUEST';
export const GET_SUB_COUNTIES_SUCCESS = 'GET_SUB_COUNTIES_SUCCESS';
export const GET_SUB_COUNTIES_FAILURE = 'GET_SUB_COUNTIES_FAILURE';

export const GET_WARDS_REQUEST = 'GET_WARDS_REQUEST';
export const GET_WARDS_SUCCESS = 'GET_WARDS_SUCCESS';
export const GET_WARDS_FAILURE = 'GET_WARDS_FAILURE';
