export const GET_FACILITIES_REQUEST = 'GET_FACILITIES_REQUEST';
export const GET_FACILITIES_SUCCESS = 'GET_FACILITIES_SUCCESS';
export const GET_FACILITIES_FAILURE = 'GET_FACILITIES_FAILURE';

export const ADD_FACILITY_REQUEST = 'ADD_FACILITY_REQUEST';
export const ADD_FACILITY_SUCCESS = 'ADD_FACILITY_SUCCESS';
export const ADD_FACILITY_FAILURE = 'ADD_FACILITY_FAILURE';

export const UPDATE_FACILITY_REQUEST = 'UPDATE_FACILITY_REQUEST';
export const UPDATE_FACILITY_SUCCESS = 'UPDATE_FACILITY_SUCCESS';
export const UPDATE_FACILITY_FAILURE = 'UPDATE_FACILITY_FAILURE';

export const DELETE_FACILITY_REQUEST = 'DELETE_FACILITY_REQUEST';
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS';
export const DELETE_FACILITY_FAILURE = 'DELETE_FACILITY_FAILURE';

export const IMPORT_FACILITIES_REQUEST = 'IMPORT_FACILITIES_REQUEST';
export const IMPORT_FACILITIES_SUCCESS = 'IMPORT_FACILITIES_SUCCESS';
export const IMPORT_FACILITIES_FAILURE = 'IMPORT_FACILITIES_FAILURE';
