export const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAIL = 'GET_REPORTS_FAIL';

export const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAIL = 'GET_REPORT_FAIL';

export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';

export const UPDATE_REPORT_REQUEST = 'UPDATE_REPORT_REQUEST';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_FAIL = 'UPDATE_REPORT_FAIL';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL';

export const ADD_RECIPIENT_REQUEST = 'ADD_RECIPIENT_REQUEST';
export const ADD_RECIPIENT_SUCCESS = 'ADD_RECIPIENT_SUCCESS';
export const ADD_RECIPIENT_FAIL = 'ADD_RECIPIENT_FAIL';

export const GET_MAIL_LIST_REQUEST = 'GET_MAIL_LIST_REQUEST';
export const GET_MAIL_LIST_SUCCESS = 'GET_MAIL_LIST_SUCCESS';
export const GET_MAIL_LIST_FAIL = 'GET_MAIL_LIST_FAIL';

export const GET_SMS_REPORTS_REQUEST = 'GET_SMS_REPORTS_REQUEST';
export const GET_SMS_REPORTS_SUCCESS = 'GET_SMS_REPORTS_SUCCESS';
export const GET_SMS_REPORTS_FAIL = 'GET_SMS_REPORTS_FAIL';

export const GET_SUBMISSIONS_BY_FORM_REQUEST =
  'GET_SUBMISSIONS_BY_FORM_REQUEST';
export const GET_SUBMISSIONS_BY_FORM_SUCCESS =
  'GET_SUBMISSIONS_BY_FORM_SUCCESS';
export const GET_SUBMISSIONS_BY_FORM_FAIL = 'GET_SUBMISSIONS_BY_FORM_FAIL';

export const GET_SUPERVISORY_REPORT_REQUEST = 'GET_SUPERVISORY_REPORT_REQUEST';
export const GET_SUPERVISORY_REPORT_SUCCESS = 'GET_SUPERVISORY_REPORT_SUCCESS';
export const GET_SUPERVISORY_REPORT_FAIL = 'GET_SUPERVISORY_REPORT_FAIL';

export const GET_LATE_PMT_REQUEST = 'GET_LATE_PMT_REQUEST';
export const GET_LATE_PMT_SUCCESS = 'GET_LATE_PMT_SUCCESS';
export const GET_LATE_PMT_FAIL = 'GET_LATE_PMT_FAIL';

export const SET_TEST_REPORT = 'SET_TEST_REPORT';

export const GET_TEST_REPORT = 'GET_TEST_REPORT';
