export const addresses = [
  {
    key: 'county',
    val: 'Homa Bay',
    county: '',
    subCounty: '',
    ward: '',
  },
  {
    key: 'county',
    val: 'Migori',
    county: '',
    subCounty: '',
    ward: '',
  },
  {
    key: 'county',
    val: 'Other',
    county: '',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Homabay Township',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Ndhiwa',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Rachuonyo East',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Rachuonyo North',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Rachuonyo South',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Rangwe',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Suba North',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Suba South',
    county: 'Homa Bay',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Awendo',
    county: 'Migori',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Nyatike',
    county: 'Migori',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Rongo',
    county: 'Migori',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Suna East',
    county: 'Migori',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Suna West',
    county: 'Migori',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Uriri',
    county: 'Migori',
    subCounty: '',
    ward: '',
  },
  {
    key: 'sub_county',
    val: 'Other',
    county: 'other',
    subCounty: '',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Homabay Central',
    county: 'Homa Bay',
    subCounty: 'Homabay Township',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Homabay East',
    county: 'Homa Bay',
    subCounty: 'Homabay Township',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kanyadoto',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kologi',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kosewe',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kwabwai',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: '',
  },
  {
    key: 'ward',
    val: 'North Kabuoch',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: '',
  },
  {
    key: 'ward',
    val: 'South Kabuoch',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kabondo East',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kabondo West',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kojwach',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kokwanyo Kakelo',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kanyaluo',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kendu town',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'North Karachuonyo',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Wang chieng',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'West Karachuonyo',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Central Kasipul',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'East Kamagak',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'South Kasipul',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'West Kamagak',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'West Kasipul',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'East Gem',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kagan',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kochia',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: '',
  },
  {
    key: 'ward',
    val: 'West Gem',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Gembe',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kasgunga',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Lambwe',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Rusinga',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Gwassi North',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Gwassi South',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kaksingiri West',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Ruma Kaksingiri East',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Central Sakwa',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'North Sakwa',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'South Sakwa',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'West Sakwa',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Got Kachola',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kachieng',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kaler',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kanyarwanda',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kanyasa',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Muhuru',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: '',
  },
  {
    key: 'ward',
    val: 'North Kadem',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Central Kamagambo',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'East Kamagambo',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'North Kamagambo',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'South Kamagambo',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: '',
  },
  {
    key: 'ward',
    val: 'God Jope',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kakrao',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Kwa',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Suna Central',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Oruba Ragana',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Suna Wasimbete',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Wasweta 2',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Wiga',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Central Kanyamkago',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: '',
  },
  {
    key: 'ward',
    val: 'East Kanyamkago',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: '',
  },
  {
    key: 'ward',
    val: 'North Kanyamkago',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: '',
  },
  {
    key: 'ward',
    val: 'South Kanyamkago',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: '',
  },
  {
    key: 'ward',
    val: 'West Kanyamkago',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: '',
  },
  {
    key: 'ward',
    val: 'Other',
    county: 'other',
    subCounty: 'other',
    ward: '',
  },
  {
    key: 'operations_site',
    val: 'CHMT Offices',
    county: 'Homa Bay',
    subCounty: 'Homabay Township',
    ward: 'Homabay Central',
  },
  {
    key: 'operations_site',
    val: 'Marindi Health Center',
    county: 'Homa Bay',
    subCounty: 'Homabay Township',
    ward: 'Homabay East',
  },
  {
    key: 'operations_site',
    val: 'Nyalkinyi Health Center',
    county: 'Homa Bay',
    subCounty: 'Homabay Township',
    ward: 'Homabay East',
  },
  {
    key: 'operations_site',
    val: 'Pala Masogo Health Center',
    county: 'Homa Bay',
    subCounty: 'Homabay Township',
    ward: 'Homabay East',
  },
  {
    key: 'operations_site',
    val: 'Nguku Dispensary',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'Kanyadoto',
  },
  {
    key: 'operations_site',
    val: 'Malela Health Centre',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'Kologi',
  },
  {
    key: 'operations_site',
    val: 'Okok dispensary',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'Kologi',
  },
  {
    key: 'operations_site',
    val: 'Ndhiwa Sub County Hospital',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'Kosewe',
  },
  {
    key: 'operations_site',
    val: 'Got Kojowi Health Center',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'Kwabwai',
  },
  {
    key: 'operations_site',
    val: 'Magina health centre',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'North Kabuoch',
  },
  {
    key: 'operations_site',
    val: 'Ombo  Kachieng',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'North Kabuoch',
  },
  {
    key: 'operations_site',
    val: 'Pala Health Centre',
    county: 'Homa Bay',
    subCounty: 'Ndhiwa',
    ward: 'South Kabuoch',
  },
  {
    key: 'operations_site',
    val: 'Othoro Sub County Hospital Hbay',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: 'Kabondo East',
  },
  {
    key: 'operations_site',
    val: 'Kabondo Sub County hospital',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: 'Kabondo West',
  },
  {
    key: 'operations_site',
    val: 'Ringa Health Center',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: 'Kojwach',
  },
  {
    key: 'operations_site',
    val: 'Ober Kakelo Chiefs camp',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo East',
    ward: 'Kokwanyo Kakelo',
  },
  {
    key: 'operations_site',
    val: 'Adiedo Health Centre',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: 'Kanyaluo',
  },
  {
    key: 'operations_site',
    val: 'Kendu Sub county Hopsital',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: 'Kendu town',
  },
  {
    key: 'operations_site',
    val: 'Wagwe Dispensary',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: 'North Karachuonyo',
  },
  {
    key: 'operations_site',
    val: 'Chuthber Dispensary',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: 'Wang chieng',
  },
  {
    key: 'operations_site',
    val: 'Homabay hills health centre',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: 'West Karachuonyo',
  },
  {
    key: 'operations_site',
    val: 'Okiki Amayo health centre',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo North',
    ward: 'West Karachuonyo',
  },
  {
    key: 'operations_site',
    val: 'Koywech Dispensary',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: 'Central Kasipul',
  },
  {
    key: 'operations_site',
    val: 'Sino Health Center',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: 'East Kamagak',
  },
  {
    key: 'operations_site',
    val: 'Nyangiela Sub County Hospital',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: 'South Kasipul',
  },
  {
    key: 'operations_site',
    val: 'Rachuonyo Sub County Hospital',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: 'West Kamagak',
  },
  {
    key: 'operations_site',
    val: 'Ombek health Center',
    county: 'Homa Bay',
    subCounty: 'Rachuonyo South',
    ward: 'West Kasipul',
  },
  {
    key: 'operations_site',
    val: 'Rariw Dispensary',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: 'East Gem',
  },
  {
    key: 'operations_site',
    val: 'Ndiru Health Center',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: 'Kagan',
  },
  {
    key: 'operations_site',
    val: 'Nyagoro Health Center',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: 'Kochia',
  },
  {
    key: 'operations_site',
    val: 'Rangwe Sub County Hospital',
    county: 'Homa Bay',
    subCounty: 'Rangwe',
    ward: 'West Gem',
  },
  {
    key: 'operations_site',
    val: 'Kitare Health Center',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: 'Gembe',
  },
  {
    key: 'operations_site',
    val: 'Mbita Sub County Hospital',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: 'Kasgunga',
  },
  {
    key: 'operations_site',
    val: 'Ogongo Sub County Hospital',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: 'Lambwe',
  },
  {
    key: 'operations_site',
    val: 'Tom Mboya Health Centre',
    county: 'Homa Bay',
    subCounty: 'Suba North',
    ward: 'Rusinga',
  },
  {
    key: 'operations_site',
    val: 'Nyandiwa Health Center',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: 'Gwassi North',
  },
  {
    key: 'operations_site',
    val: 'Magunga Health Center',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: 'Gwassi South',
  },
  {
    key: 'operations_site',
    val: 'Nyamrisa Health Center',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: 'Kaksingiri West',
  },
  {
    key: 'operations_site',
    val: 'Suba sub county Hospital',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: 'Kaksingiri West',
  },
  {
    key: 'operations_site',
    val: 'Nyatoto Health Center',
    county: 'Homa Bay',
    subCounty: 'Suba South',
    ward: 'Ruma Kaksingiri East',
  },
  {
    key: 'operations_site',
    val: 'Awendo Sub county Hospital',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: 'Central Sakwa',
  },
  {
    key: 'operations_site',
    val: 'Dede Dispensary',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: 'North Sakwa',
  },
  {
    key: 'operations_site',
    val: 'Mariwa Health Centre',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: 'South Sakwa',
  },
  {
    key: 'operations_site',
    val: 'Rabondo Dispensary',
    county: 'Migori',
    subCounty: 'Awendo',
    ward: 'West Sakwa',
  },
  {
    key: 'operations_site',
    val: 'Wath Onger Dispensary',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: 'Got Kachola',
  },
  {
    key: 'operations_site',
    val: 'Karungu Sub County Hospital',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: 'Kachieng',
  },
  {
    key: 'operations_site',
    val: 'Nyandago Koweru Dispensary',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: 'Kaler',
  },
  {
    key: 'operations_site',
    val: "Macalder Chief's Camp",
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: 'Kanyarwanda',
  },
  {
    key: 'operations_site',
    val: "Alendo Chief's Camp",
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: 'Kanyasa',
  },
  {
    key: 'operations_site',
    val: 'Muhuru Health Centre',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: 'Muhuru',
  },
  {
    key: 'operations_site',
    val: 'Agenga Dispensary',
    county: 'Migori',
    subCounty: 'Nyatike',
    ward: 'North Kadem',
  },
  {
    key: 'operations_site',
    val: 'Rongo Sub County Hospital',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: 'Central Kamagambo',
  },
  {
    key: 'operations_site',
    val: 'Kochola Dispensary',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: 'East Kamagambo',
  },
  {
    key: 'operations_site',
    val: 'Minyenya Dispensary',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: 'North Kamagambo',
  },
  {
    key: 'operations_site',
    val: 'Ongo Health Centre',
    county: 'Migori',
    subCounty: 'Rongo',
    ward: 'South Kamagambo',
  },
  {
    key: 'operations_site',
    val: 'Osingo Dispensary',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: 'God Jope',
  },
  {
    key: 'operations_site',
    val: 'Anjego Dispensary',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: 'Kakrao',
  },
  {
    key: 'operations_site',
    val: 'Suna Rabuor Health Centre',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: 'Kwa',
  },
  {
    key: 'operations_site',
    val: 'Migori County Referral Hospital',
    county: 'Migori',
    subCounty: 'Suna East',
    ward: 'Suna Central',
  },
  {
    key: 'operations_site',
    val: 'Suna Ragana Dispensary',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: 'Oruba Ragana',
  },
  {
    key: 'operations_site',
    val: 'Nyamaranga Health centre',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: 'Suna Wasimbete',
  },
  {
    key: 'operations_site',
    val: 'Bondo Dispensary',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: 'Wasweta 2',
  },
  {
    key: 'operations_site',
    val: 'Arombe Dispensary',
    county: 'Migori',
    subCounty: 'Suna West',
    ward: 'Wiga',
  },
  {
    key: 'operations_site',
    val: 'Uriri Health Centre',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: 'Central Kanyamkago',
  },
  {
    key: 'operations_site',
    val: 'Oyani Health Centre',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: 'East Kanyamkago',
  },
  {
    key: 'operations_site',
    val: 'Othoro Sub County Hospital Mgr',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: 'North Kanyamkago',
  },
  {
    key: 'operations_site',
    val: 'Bware Dispensary',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: 'South Kanyamkago',
  },
  {
    key: 'operations_site',
    val: 'Lela Dispensary',
    county: 'Migori',
    subCounty: 'Uriri',
    ward: 'West Kanyamkago',
  },
  {
    key: 'operations_site',
    val: 'Other',
    county: '',
    subCounty: '',
    ward: 'other',
  },
];

export const subCounty = facility => {
  return addresses.find(
    item => item.key === 'operations_site' && item.val === facility
  );
};
